### ISSUE TITLE
[IDEA] Double Pipe Heat Exchanger

### ISSUE THREAD

**Issue by kookma** [virajdesai0309/DWSim-Repo#1]
Thank you for all your great work.
One topic is of high pedagogical value in chemical engineering process simulation is the heat transfer study in double pipe heat exchangers.
They are simple and can be calculated by hand. So, in the class they are very handy to work with student.

See: 
https://books-library.net/files/books-library.online-06121334Xp4O0.pdf (with several examples)
https://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node131.html

It would be nice to add a section in this repo discussing double pipe exchangers.

**Comment by virajdesai0309** [comment]
Noted, will work on some illustrative examples from the sample papers and will sure upload it in the main repo with proper documentation.

Thanking you for idea
